import { ApplicationConfig, provideZoneChangeDetection, importProvidersFrom } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withXsrfConfiguration, withInterceptors } from '@angular/common/http';
import { errorInterceptor, loadingInterceptor } from './core/interceptors';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { providePrimeNG } from 'primeng/config';
import Aura from '@primeng/themes/aura';
import {
  LucideAngularModule,
  Home,
  FileText,
  BarChart3,
  BarChart2,
  Circle,
  BookOpen,
  Landmark,
  ClipboardList,
  Download,
  Eye,
  MessageCircle,
  Search,
  FolderOpen,
  Clock,
  AlertTriangle,
  CheckCircle,
  Check,
  X,
  Bell,
  AlertOctagon,
  Upload,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  Building2,
  Zap,
  FileSpreadsheet,
  File,
  Info,
  ArrowUpDown,
  ArrowUp,
  ArrowDown,
  Plus,
  Link,
  Unlink,
  LayoutDashboard,
  Briefcase,
  TrendingUp,
  TrendingDown,
  Calendar,
  Hourglass,
  Inbox,
  Loader,
  FileQuestion,
  ArrowLeft,
  SearchX,
  Coins,
  Globe,
  CalendarClock,
  Files,
  Wallet,
  Percent,
  AlertCircle,
  Bot,
  Send,
  GitCompare,
  PieChart,
  Trash2,
  HelpCircle,
  Command,
  ListTodo,
  FileCheck,
  ArrowRightLeft,
  Filter,
  RotateCcw,
  ExternalLink,
  Maximize2,
  Grid,
  List,
  MoreVertical,
  RefreshCw,
  Activity,
  Users,
  Settings,
  LogOut,
  Library,
  Folder,
  FolderTree,
  ChevronUp,
  Image,
  FileX,
  GitBranch,
  Network,
  ZoomIn,
  ZoomOut,
  Maximize,
  Move,
  MousePointer,
  Minimize2,
  Menu,
  BellOff,
} from 'lucide-angular';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    provideHttpClient(
      withXsrfConfiguration({
        cookieName: 'XSRF-TOKEN',
        headerName: 'X-XSRF-TOKEN',
      }),
      withInterceptors([loadingInterceptor, errorInterceptor])
    ),
    provideAnimationsAsync(),
    providePrimeNG({
      theme: {
        preset: Aura,
        options: {
          darkModeSelector: '.dark-mode',
          cssLayer: {
            name: 'primeng',
            order: 'tailwind-base, primeng, tailwind-utilities',
          },
        },
      },
    }),
    importProvidersFrom(
      LucideAngularModule.pick({
        Home,
        FileText,
        BarChart3,
        BarChart2,
        Circle,
        BookOpen,
        Landmark,
        ClipboardList,
        Download,
        Eye,
        MessageCircle,
        Search,
        FolderOpen,
        Clock,
        AlertTriangle,
        CheckCircle,
        Check,
        X,
        Bell,
        AlertOctagon,
        Upload,
        ChevronRight,
        ChevronLeft,
        ChevronDown,
        Building2,
        Zap,
        FileSpreadsheet,
        File,
        Info,
        ArrowUpDown,
        ArrowUp,
        ArrowDown,
        Plus,
        Link,
        Unlink,
        LayoutDashboard,
        Briefcase,
        TrendingUp,
        TrendingDown,
        Calendar,
        Hourglass,
        Inbox,
        Loader,
        FileQuestion,
        ArrowLeft,
        SearchX,
        Coins,
        Globe,
        CalendarClock,
        Files,
        Wallet,
        Percent,
        AlertCircle,
        Bot,
        Send,
        GitCompare,
        PieChart,
        Trash2,
        HelpCircle,
        Command,
        ListTodo,
        FileCheck,
        ArrowRightLeft,
        Filter,
        RotateCcw,
        ExternalLink,
        Maximize2,
        Grid,
        List,
        MoreVertical,
        RefreshCw,
        Activity,
        Users,
        Settings,
        LogOut,
        Library,
        Folder,
        FolderTree,
        ChevronUp,
        Image,
        FileX,
        GitBranch,
        Network,
        ZoomIn,
        ZoomOut,
        Maximize,
        Move,
        MousePointer,
        Minimize2,
        Menu,
        BellOff,
      })
    ),
  ],
};
